server:
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql:///db_eims?useSSL=false
    username: root
    password: KP01rndqtxSoYLwy4NJQe17/mxfPqU1ylwO9Q8CpwQ+x19QkEE4p63NkMiZzdLqK1uJWh1yfTY/ZdeMU7sERvA==
    druid:
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKs1zemhlrWq0CXzRV8n/vw0GY1x6YiPS44jcDpcM6E/imy3e76bVm0nRessjxEa+cFRgKJLMV4/xQUmke7XkV0CAwEAAQ==
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 600000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall    
      
  redis:
    host: 127.0.0.1
    port: 6379
    password: '123456'
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
    timeout: 5000
      
  mvc:
    view:
      suffix: .html
      prefix: /pages/
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/wepapp/
    
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml #mapper文件地址
  global-config:
    db-config:
      id-type: auto  #数据库id自增
      field-strategy: not-empty #字段非空判断
      table-prefix: t_ #表前缀

#logging:
#  level: 
    #root: debug